[package]
name = "hangman"
version = "0.1.0"
authors = ["Andrew Radev <andrey.radev@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "3.0.1"
rand = "0.7.3"
structopt = { version = "0.3.21", default-features = false }
structopt-derive = "0.4.14"
